# Generated by Django 3.2.13 on 2023-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so2', models.FloatField()),
                ('co', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('AQI', models.FloatField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
