# Generated by Django 3.2.13 on 2023-05-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polution',
            old_name='co',
            new_name='CO',
        ),
        migrations.RenameField(
            model_name='polution',
            old_name='no2',
            new_name='NO',
        ),
        migrations.RenameField(
            model_name='polution',
            old_name='o3',
            new_name='O3',
        ),
        migrations.RenameField(
            model_name='polution',
            old_name='pm10',
            new_name='PM10',
        ),
        migrations.RenameField(
            model_name='polution',
            old_name='pm2_5',
            new_name='PM2_5',
        ),
        migrations.RenameField(
            model_name='polution',
            old_name='so2',
            new_name='SO2',
        ),
    ]
