# Generated by Django 3.2.13 on 2023-05-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230503_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polution',
            old_name='NO',
            new_name='NO2',
        ),
    ]
