# Generated by Django 3.2.13 on 2023-05-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_no_polution_no2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_content_type', models.CharField(max_length=20)),
                ('first_data', models.IntegerField()),
            ],
        ),
    ]
